// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8XSeBN2Pl6rpnz4Ek1IwBMsf9WIm36lQ',
    appId: '1:616084783191:web:605ce6a714c0e165c56312',
    messagingSenderId: '616084783191',
    projectId: 'delivery-b94f2',
    authDomain: 'delivery-b94f2.firebaseapp.com',
    storageBucket: 'delivery-b94f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_1TpyYMNh_UhgmIuzFeAMStHLkxPS4lY',
    appId: '1:616084783191:android:bd2ff7812e1a6f97c56312',
    messagingSenderId: '616084783191',
    projectId: 'delivery-b94f2',
    storageBucket: 'delivery-b94f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYlsRywXLp8gElBGuV5lM5OO1j9tt7nmA',
    appId: '1:616084783191:ios:63fb939c450eeb25c56312',
    messagingSenderId: '616084783191',
    projectId: 'delivery-b94f2',
    storageBucket: 'delivery-b94f2.firebasestorage.app',
    iosBundleId: 'com.bilalflutter.delivary',
  );
}
